#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xD9631FEAF0CC6227 (infra-root@openstack.org)
#
Name     : oslo.config
Version  : 3.19.0
Release  : 49
URL      : http://tarballs.openstack.org/oslo.config/oslo.config-3.19.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.config/oslo.config-3.19.0.tar.gz
Source99 : http://tarballs.openstack.org/oslo.config/oslo.config-3.19.0.tar.gz.asc
Summary  : Oslo Configuration API
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.config-bin
Requires: oslo.config-python
Requires: debtcollector
Requires: netaddr
Requires: oslo.i18n
Requires: rfc3986
Requires: six
Requires: stevedore
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-Add-embeded-multi-files-parsing.patch
Patch2: 0001-stateless.patch

%description
==========================
Oslo Configuration Library
==========================

%package bin
Summary: bin components for the oslo.config package.
Group: Binaries

%description bin
bin components for the oslo.config package.


%package python
Summary: python components for the oslo.config package.
Group: Default

%description python
python components for the oslo.config package.


%prep
%setup -q -n oslo.config-3.19.0
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1493081266
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1493081266
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oslo-config-generator

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
