#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1A541148054E9E38 (infra-root@openstack.org)
#
Name     : oslo.config
Version  : 6.8.0
Release  : 59
URL      : http://tarballs.openstack.org/oslo.config/oslo.config-6.8.0.tar.gz
Source0  : http://tarballs.openstack.org/oslo.config/oslo.config-6.8.0.tar.gz
Source99 : http://tarballs.openstack.org/oslo.config/oslo.config-6.8.0.tar.gz.asc
Summary  : Oslo Configuration API
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.config-bin = %{version}-%{release}
Requires: oslo.config-license = %{version}-%{release}
Requires: oslo.config-python = %{version}-%{release}
Requires: oslo.config-python3 = %{version}-%{release}
Requires: PyYAML
Requires: debtcollector
Requires: enum34
Requires: netaddr
Requires: oslo.i18n
Requires: requests
Requires: rfc3986
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : pbr
Patch1: 0001-stateless.patch

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/oslo.config.svg
:target: https://governance.openstack.org/tc/reference/tags/index.html

%package bin
Summary: bin components for the oslo.config package.
Group: Binaries
Requires: oslo.config-license = %{version}-%{release}

%description bin
bin components for the oslo.config package.


%package license
Summary: license components for the oslo.config package.
Group: Default

%description license
license components for the oslo.config package.


%package python
Summary: python components for the oslo.config package.
Group: Default
Requires: oslo.config-python3 = %{version}-%{release}

%description python
python components for the oslo.config package.


%package python3
Summary: python3 components for the oslo.config package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.config package.


%prep
%setup -q -n oslo.config-6.8.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551028935
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.config
cp LICENSE %{buildroot}/usr/share/package-licenses/oslo.config/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oslo-config-generator
/usr/bin/oslo-config-validator

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.config/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
