#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x4F398DEAE440091C (infra-root@openstack.org)
#
Name     : oslo.config
Version  : 8.0.1
Release  : 73
URL      : http://tarballs.openstack.org/oslo.config/oslo.config-8.0.1.tar.gz
Source0  : http://tarballs.openstack.org/oslo.config/oslo.config-8.0.1.tar.gz
Source1  : http://tarballs.openstack.org/oslo.config/oslo.config-8.0.1.tar.gz.asc
Summary  : Oslo Configuration API
Group    : Development/Tools
License  : Apache-2.0
Requires: oslo.config-bin = %{version}-%{release}
Requires: oslo.config-license = %{version}-%{release}
Requires: oslo.config-python = %{version}-%{release}
Requires: oslo.config-python3 = %{version}-%{release}
Requires: PyYAML
Requires: debtcollector
Requires: netaddr
Requires: oslo.i18n
Requires: requests
Requires: rfc3986
Requires: six
Requires: stevedore
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : debtcollector
BuildRequires : netaddr
BuildRequires : oslo.i18n
BuildRequires : pbr
BuildRequires : requests
BuildRequires : rfc3986
BuildRequires : six
BuildRequires : stevedore
Patch1: 0001-stateless.patch

%description
========================
Team and repository tags
========================
.. image:: https://governance.openstack.org/tc/badges/oslo.config.svg
:target: https://governance.openstack.org/tc/reference/tags/index.html

%package bin
Summary: bin components for the oslo.config package.
Group: Binaries
Requires: oslo.config-license = %{version}-%{release}

%description bin
bin components for the oslo.config package.


%package license
Summary: license components for the oslo.config package.
Group: Default

%description license
license components for the oslo.config package.


%package python
Summary: python components for the oslo.config package.
Group: Default
Requires: oslo.config-python3 = %{version}-%{release}

%description python
python components for the oslo.config package.


%package python3
Summary: python3 components for the oslo.config package.
Group: Default
Requires: python3-core

%description python3
python3 components for the oslo.config package.


%prep
%setup -q -n oslo.config-8.0.1
cd %{_builddir}/oslo.config-8.0.1
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582741182
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oslo.config
cp %{_builddir}/oslo.config-8.0.1/LICENSE %{buildroot}/usr/share/package-licenses/oslo.config/b9a131284bb03c49a33f0ade435e87c1bff4394b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/oslo-config-generator
/usr/bin/oslo-config-validator

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oslo.config/b9a131284bb03c49a33f0ade435e87c1bff4394b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
